blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/new/', views.PostCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('comment/<int:pk>/edit/', views.CommentUpdateView.as_view(), name='comment_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/login/', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), {'next_page':''}, name='logout'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_detail')

    def __str__(self):
        return self.text

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.models import User
from django.views.generic import TemplateView,ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Comment
from .form import PostForm, CommentForm, UserCreationForm
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
# Create your views here.
class AboutView(TemplateView):
    template_name = 'blog/about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = User.objects.get(username=self.request.user)
        post.save()
        return super(PostCreateView, self).form_valid(form)

class PostUpdateView(LoginRequiredMixin ,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('create_date')

class UserCreateView(CreateView):
    template_name = 'blog/user_form.html'
    redirect_field_name = 'registration/login.html'
    form_class = UserCreationForm
    model = User

    def get_success_url(self):
        return reverse('login')

class CommentUpdateView(LoginRequiredMixin ,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = CommentForm
    model = Comment

    def get_object(self):
        comment = Comment.objects.get(pk=self.kwargs['pk'])
        comment.approved_comment = False
        comment.save()
        return comment
###########################################
###########################################

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = User.objects.get(username=request.user)
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
        return render(request, 'blog/comment_form.html', {'form':form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

blog/templates/blog/about.html
{% extends 'base.html' %}

{% block bodyblock %}
  <div class="text-center">
    <h1 style="font-family: 'Oswald', sans-serif;">About this Company:</h1>
    <h3>This is a Blogging Website, Write it Out!</h3>
  </div>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
<head>
   <title>Blog Project</title>
   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
   integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

   <!-- Alternative to Bootstrap 3 Glyphicons -->
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

   <!-- Optional theme -->
   <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

   {# MEDIUM STYLE EDITOR#}
   <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
   <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


   {# Custom CSS#}
   <link rel="stylesheet" href="{% static 'css/blog.css' %}">

   {# Fonts#}
   <link href="https://fonts.googleapis.com/css2?family=Lobster+Two:wght@700&family=Montserrat&family=Oswald&family=Tenali+Ramakrishna&display=swap" rel="stylesheet">
 </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color:#563d7c">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand mr-0 mr-md-2" href="{% url 'blog:post_list' %}">
       <img id="logo" src="{% static 'images/logo.png' %}" alt="Logo" width="100px">
      </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
         <li class="nav-item">
           <a class="nav-link" href="{% url 'blog:post_list' %}">HOME</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="{% url 'blog:about' %}">ABOUT</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="https://github.com/GaganShergill" target="_blank">GITHUB</a>
         </li>
       </ul>

       <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
         {% if user.is_authenticated %}
         <li class="nav-item">
           <a class="nav-link" href="{% url 'blog:post_new' %}">NEW POST</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="{% url 'blog:post_draft_list' %}">DRAFTS</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="{% url 'logout' %}">LOG OUT</a>
         </li>
         <li class="nav-item">
           <a class="nav-link">Welcome: {{user.username|title}}</a>
         </li>
       </ul>

       {% else %}
       <li class="nav-item" id="user-icon">
         <a class="nav-item nav-link" href="{% url 'login' %}" aria-label="Login">
         <i class="fa fa-user-circle-o fa-lg" aria-hidden="true"></i></a>
       </li>
       {% endif %}
       </ul>
      </div>
    </nav>

    <div class="container jumbotron">
      {% block bodyblock %}
      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block bodyblock %}
  <h1 class="text-center" style="font-family: 'Oswald', sans-serif">New Comment</h1>
  <form class="post-form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="save btn btn-default" value="Post Comment">
  </form>

  <script>var editor=new MediumEditor('.editable');</script>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block bodyblock %}
  <form method="POST" class="text-center">
    {% csrf_token %}
    <h4>Are you sure you want to delete <span style="font-family: 'Oswald', sans-serif;">{{object}}</span></h4>
    <input class="btn btn-danger" type="submit" value="Confirm">
    <a class="btn btn-primary" href="{% url 'blog:post_detail' pk=post.pk %}">Cancel</a>
  </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block bodyblock %}
<h1 class="posttitle text-center">{{post.title}}</h1>
{% if user.is_authenticated and user == post.author %}
<div class="postupdate">
  <a class="btn btn-primary btn-sm" href="{% url 'blog:post_edit' pk=post.pk %}">
    <i class="fa fa-pencil" aria-hidden="true"></i>
  </a>
  <a class="btn btn-primary btn-sm" href="{% url 'blog:post_remove' pk=post.pk %}">
    <i class="fa fa-times" aria-hidden="true"></i>
  </a>
</div>
{% endif %}
{% if post.published_date %}
<div class="date text-center">Author: {{post.author|title}}</div>
<div class="date text-center">{{post.published_date}}</div>
{% else %}
<div class="text-center">
  <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
</div>
{% endif %}

<div class="postcontent text-justify">{{post.text|safe|linebreaksbr}}</div>

<hr>
{% if post.published_date %}
<a class="btn btn-primary btn-comment pull-right mr-3" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

<div class="container post_detail">
  <h5>COMMENTS:</h5>
  {% for comment in post.comments.all %}
  <br>
  <div class="comments px-3 mb-2">
    {% if user == comment.author or user == post.author or comment.approved_comment %}
    <div class="comments_body px-3 mb-1">{{comment.text|safe|linebreaks}}</div>
    <div class="comments_meta">
      {% if comment.approved_comment %}
      <span>Posted By:<strong>{{comment.author|title}}</strong></span>
      {% else %}
      <span>Waiting for Approval... | Posted By:<strong>{{comment.author|title}}</strong></span>
      {% endif %}
      <div class="v1"></div>
      <span>{{comment.create_date}}</span>
    </div>
    {% if user == post.author and not comment.approved_comment %}
    <div class="comment_approve">
      <a class="btn btn-primary btn-sm" href="{% url 'blog:comment_approve' pk=comment.pk %}">
        <i class="fa fa-check" aria-hidden="true"></i>
      </a>
      <a class="btn btn-primary btn-sm" href="{% url 'blog:comment_remove' pk=comment.pk %}">
        <i class="fa fa-times" aria-hidden="true"></i>
      </a>
    </div>
    {% elif user == comment.author %}
    <div class="comment_approve">
      <a class="btn btn-primary btn-sm" href="{% url 'blog:comment_edit' pk=comment.pk %}">
        <i class="fa fa-pencil" aria-hidden="true"></i>
      </a>
      <a class="btn btn-primary btn-sm" href="{% url 'blog:comment_remove' pk=comment.pk %}">
        <i class="fa fa-times" aria-hidden="true"></i>
      </a>
    </div>
    {% endif %}

    {% endif %}
  </div>
  {% empty %}
  <span class="ml-3">No Comments</span>
  {% endfor %}
</div>
{% endif %}


{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block bodyblock %}
  <h1 class="text-center" style="font-family: 'Oswald', sans-serif">New Post</h1>
  <form class="post-form form-group" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="save btn btn-default" value="Publish">
  </form>

  <script>var editor=new MediumEditor('.editable');</script>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block bodyblock %}

  {% for post in post_list %}
    {% if request.resolver_match.url_name == 'post_list' or request.resolver_match.url_name == 'post_draft_list' and user == post.author %}
      <div class="post my-3">
        <header class="post-block_header">
          <h2 class="post-block_title"><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h2>
          <div class="post-block_meta">
            {% if post.published_date %}
              <span>Published on: {{post.published_date|date:"D M Y"}}</span>
              <span>Author: {{post.author|title}}</span>
              <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{post.approve_comments.count}}</a>
            {% else %}
              <span>Created on: {{post.create_date|date:"D M Y"}}</span>
            {% endif %}
          </div>
        </header>
        <div class="post-block_content text-justify">
          <p>{{post.text|truncatewords:30|striptags|safe}}</p>
          <a class="btn btn-primary btn-sm" href="{% url 'blog:post_detail' pk=post.pk %}">Read More</a>
        </div>
      </div>
    {% endif %}
  {% endfor %}
{% endblock %}

blog/templates/blog/user_form.html
{% extends 'blog/base.html' %}

{% block bodyblock %}
  <h1 class="my-5" style="font-family: 'Oswald', sans-serif;">Register:</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn login_btn" type="submit" name="" value="Sign Up">
  </form>
{% endblock %}